# Generated by Django 3.2.13 on 2022-06-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('text', models.TextField(blank=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
